In [17]:
import numpy as np

## Some problems. Put your answers inside the print functions

In [29]:
a = np.array([[1,0],[10,9],[-1,3]])
print("array a:")
print(a)




array a:
[[ 1  0]
 [10  9]
 [-1  3]]


In [30]:
print("\nMaximum value of a:")
print(a.max()) # put your answer inside the print

print("\nMinimum value of a:")
print(a.min()) # put your answer inside the print

print("\nReturn an array of the max in each column of a:")
print(a.max(axis=0))



print("\nReturn an array of the min in each row of a:")
print(a.min(axis=1))

print("\nReturn a, sorted within each row:")
print(np.sort(a,axis=1))

print("\nReturn a, sorted within each column:")
print(np.sort(a,axis=0))


Maximum value of a:
10

Minimum value of a:
-1

Return an array of the max in each column of a:
[10  9]

Return an array of the min in each row of a:
[ 0  9 -1]

Return a, sorted within each row:
[[ 0  1]
 [ 9 10]
 [-1  3]]

Return a, sorted within each column:
[[-1  0]
 [ 1  3]
 [10  9]]


In [54]:
b = np.arange(40).reshape((20,2))
print("array b:")
print(b)

print("\nPrint elements of the first column of b above that column's 80th percentile:")
m = np.percentile(b,80,axis=0)
print(b.all(m))

        
print("\nCovariance matrix of the columns of b:")


array b:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]

Print elements of the first column of b above that column's 80th percentile:


TypeError: only integer scalar arrays can be converted to a scalar index